name: beautiful_loading_indicator
description: testing out automated release
version: 1.0.0
repository: https://github.com/dshukertjr/beautiful_loading_indicator

environment:
  sdk: '>=2.19.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
